export const COURSES = [
  {
    id: 1,
    slug: "full-stack-development",
    title: "Full Stack Development",
    description: "Master modern web development from frontend to backend. Build production-ready applications using React, Node.js, and cloud technologies.",
    image: "/images/courses/fullstack.jpg",
    duration: "6 Months",
    level: "Intermediate",
    instructor: "Samuel Tesfaye",
    instructorBio: "10+ years experience building enterprise applications at top tech companies.",
    instructorImage: "/images/instructors/samuel.jpg",
    rating: 4.9,
    students: 1240,
    price: 4500,
    currency: "ETB",
    technologies: ["React", "Node.js", "MySQL", "AWS", "TypeScript"],
    category: "development",
    certificate: true,
    language: "English / Amharic",
    schedule: "Mon, Wed, Fri — 6:00 PM – 9:00 PM",
    modules: [
      { title: "Module 1 — HTML & CSS Fundamentals", lessons: 12 },
      { title: "Module 2 — JavaScript & TypeScript", lessons: 15 },
      { title: "Module 3 — React & Next.js", lessons: 18 },
      { title: "Module 4 — Backend APIs with Node.js", lessons: 14 },
      { title: "Module 5 — Database Design with MySQL", lessons: 10 },
      { title: "Module 6 — Cloud Deployment & DevOps", lessons: 8 },
    ],
    outcomes: [
      "Build full-stack web applications from scratch",
      "Work with REST APIs and GraphQL",
      "Deploy applications on cloud platforms",
      "Implement authentication and authorization",
      "Write clean, maintainable code",
    ],
    requirements: ["Basic computer skills", "Logical thinking ability", "Dedication to learn"],
    faqs: [
      { q: "Is this course for beginners?", a: "The course starts from basics but moves to advanced topics. Intermediate recommended." },
      { q: "Will I get a certificate?", a: "Yes, a verified certificate is issued upon completion and passing all assessments." },
      { q: "Is there a refund policy?", a: "Refunds are available within 7 days of payment if you haven't started the course." },
    ],
  },
  {
    id: 2,
    slug: "ui-ux-design",
    title: "UI/UX Design",
    description: "Learn to design stunning, user-centered digital products. Master Figma, design systems, and UX research methodologies.",
    image: "/images/courses/uiux.jpg",
    duration: "4 Months",
    level: "Beginner",
    instructor: "Hana Girma",
    instructorBio: "Lead designer with 8 years experience at international design agencies.",
    instructorImage: "/images/instructors/hana.jpg",
    rating: 4.8,
    students: 980,
    price: 3500,
    currency: "ETB",
    technologies: ["Figma", "Adobe XD", "Prototyping", "User Research"],
    category: "design",
    certificate: true,
    language: "English / Amharic",
    schedule: "Tue, Thu — 6:00 PM – 9:00 PM",
    modules: [
      { title: "Module 1 — Design Principles & Theory", lessons: 10 },
      { title: "Module 2 — Figma Mastery", lessons: 14 },
      { title: "Module 3 — UX Research & User Testing", lessons: 8 },
      { title: "Module 4 — Design Systems", lessons: 10 },
      { title: "Module 5 — Portfolio Projects", lessons: 6 },
    ],
    outcomes: [
      "Design professional UI components and screens",
      "Conduct UX research and usability testing",
      "Create interactive prototypes",
      "Build and maintain design systems",
      "Present designs to stakeholders",
    ],
    requirements: ["No prior design experience needed", "Creative mindset", "Access to a computer"],
    faqs: [
      { q: "Do I need design experience?", a: "No experience needed. We start from absolute basics." },
      { q: "Which software will I use?", a: "Primarily Figma, which has a free tier. Adobe XD is also covered." },
    ],
  },
  {
    id: 3,
    slug: "ai-engineering",
    title: "AI Engineering",
    description: "Build intelligent systems with machine learning, deep learning, and LLMs. From data preprocessing to deploying production AI models.",
    image: "/images/courses/ai.jpg",
    duration: "5 Months",
    level: "Advanced",
    instructor: "Dawit Bekele",
    instructorBio: "AI researcher and ML engineer with experience at leading tech labs.",
    instructorImage: "/images/instructors/dawit.jpg",
    rating: 4.9,
    students: 620,
    price: 5500,
    currency: "ETB",
    technologies: ["Python", "TensorFlow", "PyTorch", "OpenAI API", "LangChain"],
    category: "ai",
    certificate: true,
    language: "English",
    schedule: "Sat, Sun — 9:00 AM – 1:00 PM",
    modules: [
      { title: "Module 1 — Python for AI", lessons: 12 },
      { title: "Module 2 — Machine Learning Fundamentals", lessons: 16 },
      { title: "Module 3 — Deep Learning & Neural Networks", lessons: 14 },
      { title: "Module 4 — Natural Language Processing", lessons: 12 },
      { title: "Module 5 — LLMs & AI Applications", lessons: 10 },
    ],
    outcomes: [
      "Build and train machine learning models",
      "Work with neural networks and deep learning",
      "Integrate AI APIs into applications",
      "Deploy ML models to production",
      "Build LLM-powered applications",
    ],
    requirements: ["Python basics required", "Mathematics fundamentals", "Strong logical thinking"],
    faqs: [
      { q: "How much Python knowledge is needed?", a: "Basic Python syntax and OOP concepts are required before joining." },
      { q: "Will we work on real projects?", a: "Yes, every module includes hands-on projects with real datasets." },
    ],
  },
  {
    id: 4,
    slug: "graphic-design",
    title: "Graphic Design",
    description: "Master visual communication with Adobe Creative Suite. Create logos, branding, marketing materials, and digital artwork.",
    image: "/images/courses/graphic.jpg",
    duration: "3 Months",
    level: "Beginner",
    instructor: "Meron Tadesse",
    instructorBio: "Award-winning graphic designer with 7 years in the industry.",
    instructorImage: "/images/instructors/meron.jpg",
    rating: 4.7,
    students: 1560,
    price: 2500,
    currency: "ETB",
    technologies: ["Photoshop", "Illustrator", "InDesign", "Canva"],
    category: "design",
    certificate: true,
    language: "Amharic / English",
    schedule: "Mon, Wed — 5:00 PM – 8:00 PM",
    modules: [
      { title: "Module 1 — Design Fundamentals", lessons: 8 },
      { title: "Module 2 — Adobe Photoshop", lessons: 12 },
      { title: "Module 3 — Adobe Illustrator", lessons: 12 },
      { title: "Module 4 — Logo & Branding Design", lessons: 10 },
      { title: "Module 5 — Print & Digital Design", lessons: 8 },
    ],
    outcomes: [
      "Create professional logos and brand identities",
      "Design marketing materials and posters",
      "Manipulate photos professionally",
      "Build a portfolio of design work",
    ],
    requirements: ["No prior experience needed", "Creative interest", "Computer access"],
    faqs: [
      { q: "Is this course online or in-person?", a: "Both options are available. Online via Zoom and in-person at our campus." },
    ],
  },
  {
    id: 5,
    slug: "digital-marketing",
    title: "Digital Marketing",
    description: "Master SEO, social media marketing, paid ads, content strategy, and analytics to grow businesses in the digital age.",
    image: "/images/courses/marketing.jpg",
    duration: "3 Months",
    level: "Beginner",
    instructor: "Tigist Alemu",
    instructorBio: "Digital marketing strategist who has managed campaigns for 50+ brands.",
    instructorImage: "/images/instructors/tigist.jpg",
    rating: 4.8,
    students: 2100,
    price: 2800,
    currency: "ETB",
    technologies: ["Google Ads", "Meta Ads", "SEO Tools", "Analytics", "Mailchimp"],
    category: "marketing",
    certificate: true,
    language: "Amharic / English",
    schedule: "Tue, Thu, Sat — 4:00 PM – 6:00 PM",
    modules: [
      { title: "Module 1 — Digital Marketing Overview", lessons: 6 },
      { title: "Module 2 — SEO & Content Marketing", lessons: 10 },
      { title: "Module 3 — Social Media Marketing", lessons: 10 },
      { title: "Module 4 — Paid Advertising (Google & Meta)", lessons: 12 },
      { title: "Module 5 — Analytics & Reporting", lessons: 8 },
    ],
    outcomes: [
      "Run effective paid advertising campaigns",
      "Optimize websites for search engines",
      "Create engaging social media strategies",
      "Measure and analyze marketing performance",
    ],
    requirements: ["No prior experience needed", "Smartphone or computer", "Business mindset"],
    faqs: [
      { q: "Can I freelance after this course?", a: "Absolutely. Most of our graduates freelance or work at agencies within 3 months." },
    ],
  },
  {
    id: 6,
    slug: "mobile-app-development",
    title: "Mobile App Development",
    description: "Build cross-platform mobile apps for iOS and Android using React Native and Flutter. From concept to App Store deployment.",
    image: "/images/courses/mobile.jpg",
    duration: "5 Months",
    level: "Intermediate",
    instructor: "Yonas Haile",
    instructorBio: "Mobile developer with 30+ published apps on the App Store and Play Store.",
    instructorImage: "/images/instructors/yonas.jpg",
    rating: 4.8,
    students: 740,
    price: 4800,
    currency: "ETB",
    technologies: ["React Native", "Flutter", "Firebase", "TypeScript"],
    category: "development",
    certificate: true,
    language: "English",
    schedule: "Mon, Wed, Fri — 7:00 PM – 10:00 PM",
    modules: [
      { title: "Module 1 — Mobile Development Fundamentals", lessons: 8 },
      { title: "Module 2 — React Native Core", lessons: 16 },
      { title: "Module 3 — Flutter Introduction", lessons: 12 },
      { title: "Module 4 — Backend Integration & Firebase", lessons: 10 },
      { title: "Module 5 — App Store Deployment", lessons: 6 },
    ],
    outcomes: [
      "Build production-ready mobile applications",
      "Publish apps to App Store and Play Store",
      "Integrate real-time databases and authentication",
      "Implement push notifications and payments",
    ],
    requirements: ["JavaScript basics required", "Programming fundamentals", "Laptop with 8GB+ RAM"],
    faqs: [
      { q: "Do I need a Mac for iOS development?", a: "For React Native, Windows is fine. For native iOS testing, a Mac or remote Mac access is needed." },
    ],
  },
  {
    id: 7,
    slug: "cybersecurity",
    title: "Cybersecurity",
    description: "Learn ethical hacking, network security, penetration testing, and digital forensics. Prepare for global security certifications.",
    image: "/images/courses/cyber.jpg",
    duration: "6 Months",
    level: "Intermediate",
    instructor: "Abebe Worku",
    instructorBio: "Certified ethical hacker and cybersecurity consultant for government agencies.",
    instructorImage: "/images/instructors/abebe.jpg",
    rating: 4.9,
    students: 430,
    price: 5000,
    currency: "ETB",
    technologies: ["Kali Linux", "Metasploit", "Wireshark", "Python", "Network Security"],
    category: "security",
    certificate: true,
    language: "English",
    schedule: "Sat, Sun — 2:00 PM – 6:00 PM",
    modules: [
      { title: "Module 1 — Networking Fundamentals", lessons: 10 },
      { title: "Module 2 — Linux for Security", lessons: 10 },
      { title: "Module 3 — Ethical Hacking & Penetration Testing", lessons: 16 },
      { title: "Module 4 — Web Application Security", lessons: 12 },
      { title: "Module 5 — Digital Forensics & Incident Response", lessons: 10 },
    ],
    outcomes: [
      "Conduct professional penetration tests",
      "Identify and exploit vulnerabilities ethically",
      "Secure web applications and networks",
      "Prepare for CEH and CompTIA Security+ certifications",
    ],
    requirements: ["Networking basics required", "Linux familiarity helpful", "Python basics beneficial"],
    faqs: [
      { q: "Is this course legal?", a: "All techniques are taught in controlled lab environments for ethical, defensive purposes only." },
    ],
  },
  {
    id: 8,
    slug: "video-editing",
    title: "Video Editing",
    description: "Master professional video editing with Premiere Pro, After Effects, and DaVinci Resolve. Create cinematic content for brands and social media.",
    image: "/images/courses/video.jpg",
    duration: "2 Months",
    level: "Beginner",
    instructor: "Kaleb Tesfaye",
    instructorBio: "Filmmaker and video producer who has created content for major Ethiopian brands.",
    instructorImage: "/images/instructors/kaleb.jpg",
    rating: 4.7,
    students: 1890,
    price: 2000,
    currency: "ETB",
    technologies: ["Premiere Pro", "After Effects", "DaVinci Resolve", "Audition"],
    category: "creative",
    certificate: true,
    language: "Amharic / English",
    schedule: "Tue, Thu — 5:00 PM – 8:00 PM",
    modules: [
      { title: "Module 1 — Video Editing Basics", lessons: 8 },
      { title: "Module 2 — Adobe Premiere Pro", lessons: 12 },
      { title: "Module 3 — Motion Graphics with After Effects", lessons: 10 },
      { title: "Module 4 — Color Grading with DaVinci", lessons: 8 },
    ],
    outcomes: [
      "Edit professional video content",
      "Create motion graphics and animations",
      "Grade footage for cinematic look",
      "Export optimized content for all platforms",
    ],
    requirements: ["No prior experience needed", "Computer with 16GB RAM recommended", "Creative passion"],
    faqs: [
      { q: "What computer specs do I need?", a: "Minimum 8GB RAM, dedicated GPU recommended for After Effects." },
    ],
  },
];

export const SERVICES = [
  {
    id: 1,
    icon: "Code",
    title: "Software Development",
    description: "Custom enterprise-grade software solutions built with cutting-edge technologies tailored to your business needs.",
    color: "#00d4ff",
    details: [
      "Full-stack web & desktop application development",
      "API design, microservices & cloud-native architecture",
      "Database design, optimization & migration",
      "Ongoing maintenance, support & performance tuning",
    ],
  },
  {
    id: 2,
    icon: "Smartphone",
    title: "Mobile App Development",
    description: "Cross-platform iOS and Android applications with seamless user experiences and high performance.",
    color: "#7c3aed",
    details: [
      "React Native & Flutter cross-platform apps",
      "Native iOS (Swift) and Android (Kotlin) development",
      "App Store & Google Play publishing & optimization",
      "Push notifications, offline support & analytics",
    ],
  },
  {
    id: 3,
    icon: "Globe",
    title: "Website Development",
    description: "Modern, fast, and scalable websites from landing pages to complex web platforms.",
    color: "#10b981",
    details: [
      "Landing pages, corporate sites & e-commerce stores",
      "Next.js, React & headless CMS integrations",
      "SEO-optimized, accessible & mobile-first builds",
      "Performance audits, hosting setup & deployment",
    ],
  },
  {
    id: 4,
    icon: "Brain",
    title: "AI Solutions",
    description: "Intelligent automation, machine learning models, and AI-powered systems to transform your business operations.",
    color: "#f59e0b",
    details: [
      "Custom ML model training & deployment",
      "Chatbots, virtual assistants & NLP pipelines",
      "Predictive analytics & data intelligence dashboards",
      "AI integration into existing business workflows",
    ],
  },
  {
    id: 5,
    icon: "Palette",
    title: "UI/UX Design",
    description: "User-centered design that converts visitors to customers. Beautiful, intuitive interfaces that delight users.",
    color: "#ec4899",
    details: [
      "User research, personas & journey mapping",
      "Wireframes, prototypes & interactive mockups",
      "Design systems, component libraries & style guides",
      "Usability testing & conversion rate optimization",
    ],
  },
  {
    id: 6,
    icon: "Zap",
    title: "Branding & Identity",
    description: "Complete brand identity creation — logos, style guides, brand strategy, and visual communication systems.",
    color: "#06b6d4",
    details: [
      "Logo design & full visual identity package",
      "Brand strategy, tone of voice & positioning",
      "Marketing collateral — print, digital & social",
      "Brand guidelines & asset management",
    ],
  },
  {
    id: 7,
    icon: "TrendingUp",
    title: "Digital Marketing",
    description: "Data-driven marketing strategies, SEO, paid ads, and social media management to grow your online presence.",
    color: "#84cc16",
    details: [
      "SEO audits, keyword strategy & on-page optimization",
      "Google Ads, Meta Ads & paid social campaigns",
      "Social media content creation & community management",
      "Monthly analytics reports & performance reviews",
    ],
  },
  {
    id: 8,
    icon: "Shield",
    title: "CCTV Intelligence Systems",
    description: "AI-powered surveillance solutions with facial recognition, anomaly detection, and real-time monitoring.",
    color: "#f97316",
    details: [
      "AI-powered facial recognition & access control",
      "Real-time anomaly & intrusion detection alerts",
      "Remote monitoring dashboards & mobile apps",
      "Hardware procurement, installation & ongoing support",
    ],
  },
];

export const TEAM_MEMBERS = [
  {
    id: 1,
    name: "Biruk Alemu",
    position: "CEO & Founder",
    bio: "Visionary entrepreneur driving DreamMore's mission to empower Africa through digital innovation.",
    specialties: ["Strategy", "Leadership", "Product Vision"],
    image: "/images/team/biruk.jpg",
    linkedin: "#",
    twitter: "#",
  },
  {
    id: 2,
    name: "Sara Bekele",
    position: "CTO",
    bio: "Full-stack architect with 12 years of experience building scalable systems for global companies.",
    specialties: ["Architecture", "Cloud", "AI Systems"],
    image: "/images/team/sara.jpg",
    linkedin: "#",
    twitter: "#",
  },
  {
    id: 3,
    name: "Mikael Hailu",
    position: "Head of Academy",
    bio: "Education innovator passionate about making world-class tech education accessible across Africa.",
    specialties: ["Curriculum Design", "EdTech", "Mentorship"],
    image: "/images/team/mikael.jpg",
    linkedin: "#",
    twitter: "#",
  },
  {
    id: 4,
    name: "Liya Tadesse",
    position: "Lead Designer",
    bio: "Award-winning designer crafting premium digital experiences that bridge beauty and functionality.",
    specialties: ["UI/UX", "Brand Identity", "Motion Design"],
    image: "/images/team/liya.jpg",
    linkedin: "#",
    twitter: "#",
  },
  {
    id: 5,
    name: "Naol Girma",
    position: "AI Engineer",
    bio: "Machine learning researcher building next-generation AI solutions for African enterprises.",
    specialties: ["Machine Learning", "NLP", "Computer Vision"],
    image: "/images/team/naol.jpg",
    linkedin: "#",
    twitter: "#",
  },
  {
    id: 6,
    name: "Selamawit Worku",
    position: "Marketing Director",
    bio: "Digital marketing strategist who has scaled brands from zero to industry leaders.",
    specialties: ["Growth Marketing", "SEO", "Brand Strategy"],
    image: "/images/team/selamawit.jpg",
    linkedin: "#",
    twitter: "#",
  },
];

export const BLOG_POSTS = [
  {
    id: 1,
    slug: "future-of-ai-in-africa",
    title: "The Future of AI in Africa: Opportunities and Challenges",
    excerpt: "Artificial intelligence is reshaping industries worldwide. Here's how Africa can lead the next wave of AI innovation.",
    category: "AI",
    author: "Dawit Bekele",
    authorImage: "/images/team/dawit.jpg",
    date: "2024-12-15",
    readTime: "8 min read",
    image: "/images/blog/ai-africa.jpg",
    featured: true,
  },
  {
    id: 2,
    slug: "web3-and-blockchain-opportunities",
    title: "Web3 Development: Building the Decentralized Future",
    excerpt: "Blockchain technology is creating new opportunities for developers. Learn how to position yourself for this emerging field.",
    category: "Technology",
    author: "Samuel Tesfaye",
    authorImage: "/images/team/samuel.jpg",
    date: "2024-12-10",
    readTime: "6 min read",
    image: "/images/blog/web3.jpg",
    featured: false,
  },
  {
    id: 3,
    slug: "ethiopian-startup-ecosystem",
    title: "Ethiopia's Growing Tech Startup Ecosystem",
    excerpt: "From Addis Ababa's innovation hubs to international investment, Ethiopia is becoming Africa's next tech powerhouse.",
    category: "Startups",
    author: "Biruk Alemu",
    authorImage: "/images/team/biruk.jpg",
    date: "2024-12-05",
    readTime: "5 min read",
    image: "/images/blog/startup.jpg",
    featured: false,
  },
  {
    id: 4,
    slug: "cybersecurity-best-practices-2025",
    title: "Cybersecurity Best Practices for African Businesses in 2025",
    excerpt: "As cyber threats grow more sophisticated, Ethiopian businesses must adopt robust security frameworks to protect their assets.",
    category: "Cybersecurity",
    author: "Abebe Worku",
    authorImage: "/images/team/abebe.jpg",
    date: "2024-11-28",
    readTime: "7 min read",
    image: "/images/blog/cyber.jpg",
    featured: false,
  },
  {
    id: 5,
    slug: "learning-to-code-in-africa",
    title: "Why Learning to Code is the Best Investment for African Youth",
    excerpt: "Programming skills open doors to global opportunities. Here's why every young African should learn to code.",
    category: "Education",
    author: "Mikael Hailu",
    authorImage: "/images/team/mikael.jpg",
    date: "2024-11-20",
    readTime: "4 min read",
    image: "/images/blog/coding.jpg",
    featured: false,
  },
  {
    id: 6,
    slug: "remote-work-digital-nomad",
    title: "How African Tech Talent is Competing on the Global Stage",
    excerpt: "Remote work has leveled the playing field. African developers are landing high-paying international contracts.",
    category: "Innovation",
    author: "Sara Bekele",
    authorImage: "/images/team/sara.jpg",
    date: "2024-11-15",
    readTime: "5 min read",
    image: "/images/blog/remote.jpg",
    featured: false,
  },
];

export const PORTFOLIO_PROJECTS = [
  {
    id: 1,
    title: "EthioHealth Platform",
    category: "websites",
    description: "A comprehensive telemedicine platform connecting patients with doctors across Ethiopia.",
    technologies: ["Next.js", "Node.js", "MySQL", "AWS"],
    image: "/images/portfolio/ethiohealth.jpg",
    liveUrl: "#",
    caseStudyUrl: "#",
  },
  {
    id: 2,
    title: "AgroConnect Mobile App",
    category: "mobile apps",
    description: "Mobile marketplace connecting farmers directly with buyers, eliminating middlemen.",
    technologies: ["React Native", "Firebase", "Node.js"],
    image: "/images/portfolio/agroconnect.jpg",
    liveUrl: "#",
    caseStudyUrl: "#",
  },
  {
    id: 3,
    title: "BankDash Admin System",
    category: "dashboards",
    description: "Enterprise banking dashboard with real-time analytics and fraud detection.",
    technologies: ["React", "D3.js", "Python", "PostgreSQL"],
    image: "/images/portfolio/bankdash.jpg",
    liveUrl: "#",
    caseStudyUrl: "#",
  },
  {
    id: 4,
    title: "SafeCity AI Surveillance",
    category: "AI systems",
    description: "Smart city surveillance system with AI-powered anomaly detection and facial recognition.",
    technologies: ["Python", "TensorFlow", "OpenCV", "RTSP"],
    image: "/images/portfolio/safecity.jpg",
    liveUrl: "#",
    caseStudyUrl: "#",
  },
  {
    id: 5,
    title: "Addis Brand Identity",
    category: "branding projects",
    description: "Complete rebrand for a major Ethiopian hospitality chain — logo, style guide, and print materials.",
    technologies: ["Illustrator", "Photoshop", "Figma"],
    image: "/images/portfolio/addisbrand.jpg",
    liveUrl: "#",
    caseStudyUrl: "#",
  },
  {
    id: 6,
    title: "SchoolGuard CCTV System",
    category: "security systems",
    description: "Intelligent CCTV management system for 50+ school campuses with centralized monitoring.",
    technologies: ["Python", "AI Vision", "CCTV Integration", "Dashboard"],
    image: "/images/portfolio/schoolguard.jpg",
    liveUrl: "#",
    caseStudyUrl: "#",
  },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: "Abebe Kebede",
    company: "Kebede Imports",
    role: "CEO",
    text: "DreamMore transformed our business with a world-class e-commerce platform. Our online sales increased by 300% within 3 months of launch.",
    rating: 5,
    image: "/images/testimonials/abebe.jpg",
  },
  {
    id: 2,
    name: "Tigist Hailu",
    company: "EduTech Ethiopia",
    role: "Founder",
    text: "The team at DreamMore built our entire learning management system. Their professionalism and technical expertise are unmatched in Ethiopia.",
    rating: 5,
    image: "/images/testimonials/tigist.jpg",
  },
  {
    id: 3,
    name: "Yonas Tesfaye",
    company: "StartupAddis",
    role: "Product Manager",
    text: "From branding to mobile app, DreamMore handled everything seamlessly. Our app has 50,000+ downloads since launch.",
    rating: 5,
    image: "/images/testimonials/yonas.jpg",
  },
];
