-- Dream More Academy - Complete Courses Insert
-- Generated from promotional material
-- All 16 courses with realistic details

INSERT INTO courses (
  slug, title, description, short_description, image, duration, level, 
  instructor, instructor_bio, price, currency, category, 
  language, schedule, certificate, status
) VALUES 

-- 1. Graphics Designing
('graphics-designing', 
 'Graphics Designing', 
 'Master the art of visual communication with our comprehensive Graphics Designing course. Learn industry-standard tools including Adobe Photoshop, Illustrator, and InDesign. Create stunning logos, branding materials, social media graphics, and marketing collateral. This course covers color theory, typography, layout design, and portfolio development. Perfect for creative individuals looking to start a career in design or enhance their existing skills.',
 'Learn Adobe Photoshop, Illustrator & InDesign. Create stunning visuals, logos, and branding materials.',
 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=800',
 '12 weeks',
 'Beginner',
 'Kidus Tadesse',
 'Professional graphic designer with 8+ years experience. Former creative director at top Ethiopian agency.',
 4500.00,
 'ETB',
 'Design',
 'English / Amharic',
 'Monday, Wednesday, Friday - 2:00 PM to 5:00 PM',
 TRUE,
 'active'),

-- 2. Video Editing
('video-editing',
 'Video Editing',
 'Transform raw footage into compelling stories with our Video Editing course. Master Adobe Premiere Pro, After Effects, and DaVinci Resolve. Learn cutting techniques, color grading, motion graphics, sound design, and visual effects. From YouTube content to professional films, gain skills to excel in the booming video content industry.',
 'Master Premiere Pro & After Effects. Learn professional editing, color grading, and motion graphics.',
 'https://images.unsplash.com/photo-1536240478700-b869070f9279?w=800',
 '10 weeks',
 'Beginner',
 'Dawit Mekonnen',
 'Award-winning video editor with experience in documentary and commercial filmmaking.',
 5000.00,
 'ETB',
 'Media',
 'English / Amharic',
 'Tuesday, Thursday, Saturday - 10:00 AM to 1:00 PM',
 TRUE,
 'active'),

-- 3. Digital Marketing
('digital-marketing',
 'Digital Marketing',
 'Become a digital marketing expert with our comprehensive course covering SEO, social media marketing, email campaigns, content marketing, and paid advertising. Learn to use Google Analytics, Facebook Ads Manager, and marketing automation tools. Develop data-driven strategies to grow businesses online and drive measurable results.',
 'Master SEO, social media, Google Ads & analytics. Learn to grow businesses and drive online sales.',
 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800',
 '8 weeks',
 'Beginner',
 'Hiwot Alemu',
 'Digital marketing strategist with 6+ years helping Ethiopian businesses grow online presence.',
 4000.00,
 'ETB',
 'Marketing',
 'English / Amharic',
 'Monday, Wednesday - 5:00 PM to 8:00 PM',
 TRUE,
 'active'),

-- 4. Cinematography
('cinematography',
 'Cinematography',
 'Learn the art and science of filmmaking with our Cinematography course. Master camera operation, lighting techniques, composition, and visual storytelling. Work with professional DSLR and cinema cameras. Understand exposure, lenses, movement, and the creative decisions that make compelling visual narratives.',
 'Master camera operation, lighting & composition. Learn professional filmmaking and visual storytelling.',
 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=800',
 '14 weeks',
 'Intermediate',
 'Yonas Bekele',
 'Professional cinematographer with credits in feature films and commercial productions.',
 6500.00,
 'ETB',
 'Media',
 'English / Amharic',
 'Saturday, Sunday - 9:00 AM to 4:00 PM',
 TRUE,
 'active'),

-- 5. Web and Mobile App Development
('web-mobile-development',
 'Web and Mobile App Development',
 'Build modern web and mobile applications from scratch. Learn HTML5, CSS3, JavaScript, React, React Native, Node.js, and database design. Create responsive websites and cross-platform mobile apps. Master version control with Git and deploy applications to cloud platforms.',
 'Learn React, Node.js, React Native & more. Build responsive websites and mobile apps from scratch.',
 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800',
 '16 weeks',
 'Beginner',
 'Solomon Girma',
 'Full-stack developer with 7+ years building enterprise web and mobile applications.',
 8000.00,
 'ETB',
 'Technology',
 'English / Amharic',
 'Monday, Wednesday, Friday - 6:00 PM to 9:00 PM',
 TRUE,
 'active'),

-- 6. Programming Language C++
('cpp-programming',
 'Programming Language C++',
 'Master C++ programming from fundamentals to advanced concepts. Learn object-oriented programming, data structures, algorithms, memory management, and STL. Build real-world applications including games, system software, and performance-critical programs. Foundation for competitive programming and software engineering.',
 'Master C++ from basics to advanced OOP. Learn data structures, algorithms & build real applications.',
 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=800',
 '12 weeks',
 'Intermediate',
 'Bereket Hailu',
 'Software engineer with expertise in system programming and game development using C++.',
 5500.00,
 'ETB',
 'Technology',
 'English / Amharic',
 'Tuesday, Thursday - 2:00 PM to 5:00 PM',
 TRUE,
 'active'),

-- 7. Basic Computer Skills
('basic-computer',
 'Basic Computer Skills',
 'Essential computer literacy course covering Windows/OS operation, Microsoft Office Suite (Word, Excel, PowerPoint), internet usage, email management, and basic troubleshooting. Perfect for beginners entering the digital world or professionals wanting to improve productivity.',
 'Learn Windows, MS Office, internet & email. Perfect for beginners entering the digital world.',
 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800',
 '6 weeks',
 'Beginner',
 'Tigist Hailu',
 'IT trainer with 10+ years teaching computer literacy to diverse learners across Ethiopia.',
 2500.00,
 'ETB',
 'Foundation',
 'English / Amharic',
 'Monday, Wednesday, Friday - 10:00 AM to 12:00 PM',
 TRUE,
 'active'),

-- 8. Computer Maintenance
('computer-maintenance',
 'Computer Maintenance',
 'Learn hardware and software maintenance for desktop and laptop computers. Master component installation, operating system setup, virus removal, data recovery, networking basics, and preventive maintenance. Start a career in IT support or save money fixing your own devices.',
 'Learn hardware repair, OS installation, virus removal & networking. Start your IT support career.',
 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800',
 '8 weeks',
 'Beginner',
 'Meron Alemu',
 'Certified IT technician with expertise in hardware repair and system administration.',
 3500.00,
 'ETB',
 'Technology',
 'English / Amharic',
 'Tuesday, Thursday - 9:00 AM to 12:00 PM',
 TRUE,
 'active'),

-- 9. Mobile Maintenance
('mobile-maintenance',
 'Mobile Maintenance',
 'Specialized training in smartphone and tablet repair. Learn screen replacement, battery replacement, charging port repair, software troubleshooting, and micro-soldering techniques. Work with Android and iOS devices. High-demand skills for starting your own repair business.',
 'Master smartphone & tablet repair. Learn screen replacement, battery repair & micro-soldering.',
 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800',
 '10 weeks',
 'Beginner',
 'Getachew Kebede',
 'Mobile repair expert with 5+ years running successful repair shops in Addis Ababa.',
 4000.00,
 'ETB',
 'Technology',
 'English / Amharic',
 'Saturday, Sunday - 2:00 PM to 6:00 PM',
 TRUE,
 'active'),

-- 10. AI for Business
('ai-business',
 'AI for Business',
 'Leverage artificial intelligence to transform your business operations. Learn about AI tools for automation, data analysis, customer service chatbots, content generation, and decision-making. Understand machine learning basics and implement AI solutions without coding.',
 'Learn AI tools for automation, analytics & customer service. Transform your business with AI.',
 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800',
 '6 weeks',
 'Beginner',
 'Abebe Tadesse',
 'AI consultant helping Ethiopian businesses adopt modern AI tools and automation.',
 4500.00,
 'ETB',
 'Business',
 'English / Amharic',
 'Monday, Wednesday - 6:00 PM to 9:00 PM',
 TRUE,
 'active'),

-- 11. Cybersecurity & Data Safety
('cybersecurity',
 'Cybersecurity & Data Safety',
 'Protect digital assets with comprehensive cybersecurity training. Learn network security, ethical hacking basics, threat detection, data protection, encryption, and security best practices. Understand compliance requirements and how to secure personal and business data from modern cyber threats.',
 'Learn network security, ethical hacking & data protection. Protect against modern cyber threats.',
 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800',
 '12 weeks',
 'Intermediate',
 'Daniel Assefa',
 'Cybersecurity professional with certifications in ethical hacking and network security.',
 7000.00,
 'ETB',
 'Technology',
 'English / Amharic',
 'Tuesday, Thursday, Saturday - 5:00 PM to 8:00 PM',
 TRUE,
 'active'),

-- 12. Sales & Career Development
('sales-career',
 'Sales & Career Development',
 'Master the art of selling and accelerate your career growth. Learn sales psychology, negotiation techniques, relationship building, CRM tools, and modern sales strategies. Develop soft skills, personal branding, resume writing, interview techniques, and career planning.',
 'Master sales psychology, negotiation & CRM tools. Build soft skills & accelerate career growth.',
 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800',
 '8 weeks',
 'Beginner',
 'Hanna Girma',
 'Sales coach and career consultant with experience in corporate training and recruitment.',
 3500.00,
 'ETB',
 'Business',
 'English / Amharic',
 'Saturday, Sunday - 10:00 AM to 1:00 PM',
 TRUE,
 'active'),

-- 13. Robotics & Drone Technology
('robotics-drone',
 'Robotics & Drone Technology',
 'Explore the future with hands-on robotics and drone training. Learn Arduino programming, sensor integration, robot building, drone piloting, aerial photography, and automation basics. Build your own robots and understand IoT fundamentals.',
 'Learn Arduino, build robots & master drone piloting. Explore automation and IoT fundamentals.',
 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=800',
 '12 weeks',
 'Intermediate',
 'Fikreab Tekle',
 'Robotics engineer and certified drone pilot with passion for STEM education.',
 6000.00,
 'ETB',
 'Technology',
 'English / Amharic',
 'Friday, Saturday - 1:00 PM to 5:00 PM',
 TRUE,
 'active'),

-- 14. English Language
('english-language',
 'English Language',
 'Comprehensive English course covering speaking, listening, reading, and writing skills. Improve grammar, vocabulary, pronunciation, and business communication. Prepare for international exams or enhance professional communication. Interactive sessions with native-level instructors.',
 'Improve speaking, writing, grammar & business English. Interactive sessions for all levels.',
 'https://images.unsplash.com/photo-1543269865-cbf427effbad?w=800',
 '16 weeks',
 'Beginner',
 'Sarah Johnson',
 'TESOL certified instructor with 8+ years teaching English to international students.',
 4000.00,
 'ETB',
 'Language',
 'English',
 'Monday, Tuesday, Wednesday, Thursday - 4:00 PM to 6:00 PM',
 TRUE,
 'active'),

-- 15. AI-Powered Freelancing
('ai-freelancing',
 'AI-Powered Freelancing',
 'Launch your freelance career using cutting-edge AI tools. Learn to use AI for content creation, graphic design, coding assistance, writing, and productivity. Master freelance platforms like Upwork and Fiverr, client communication, pricing strategies, and building a sustainable remote income.',
 'Use AI tools to freelance in writing, design & coding. Master Upwork/Fiverr & build remote income.',
 'https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?w=800',
 '8 weeks',
 'Beginner',
 'Meskerem Asfaw',
 'Successful freelancer earning 6 figures through Upwork, teaching others to work remotely.',
 4500.00,
 'ETB',
 'Business',
 'English / Amharic',
 'Tuesday, Thursday - 6:00 PM to 9:00 PM',
 TRUE,
 'active'),

-- 16. 3D Modeling & Product Prototyping
('3d-modeling',
 '3D Modeling & Product Prototyping',
 'Create three-dimensional models and product prototypes using industry-standard software. Learn Blender, Fusion 360, or SketchUp for modeling, texturing, rendering, and 3D printing preparation. Design products for manufacturing, architecture, gaming, or animation.',
 'Learn Blender & Fusion 360. Create 3D models, renderings & prepare designs for 3D printing.',
 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800',
 '12 weeks',
 'Beginner',
 'Yared Solomon',
 'Product designer specializing in 3D visualization and rapid prototyping for manufacturing.',
 5500.00,
 'ETB',
 'Design',
 'English / Amharic',
 'Wednesday, Friday - 2:00 PM to 6:00 PM',
 TRUE,
 'active');

-- Insert successful message
SELECT '16 courses inserted successfully!' AS message;
